language: rust
rust:
- nightly
cache: cargo
addons:
  postgresql: '9.4'
before_script:
- "(cargo install diesel_cli || true)"
- export PATH=$HOME/.cargo/bin:$PATH
- cp .env.sample .env
- diesel setup
deploy:
  provider: heroku
  app: rust-contributors
  on:
    repo: rust-lang-nursery/thanks
